
services:  
  C1:
    build:
      context: ./c1/
    container_name: c1
    tty: true
    stdin_open: true
    networks:
      - mynet

  C2:
    build:
      context: ./c2/
    container_name: c2
    tty: true
    stdin_open: true
    networks:
      - mynet
    
  C3:
    build:
      context: ./c3/
    container_name: c3
    tty: true
    stdin_open: true
    networks:
      - mynet

  C4:
    build:
      context: ./c4/
    container_name: c4s1
    tty: true
    stdin_open: true
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

