services:
  c1:
    build:
      context: .
      dockerfile: superimage.dockerfile
      args:
        - version=16.10
    container_name: c1
    tty: true
    stdin_open: true
  c2:
    build:
      context: .
      dockerfile: superimage.dockerfile
      args:
        - version=18.10
    container_name: c2
    tty: true
    stdin_open: true
  c3:
    build:
      context: .
      dockerfile: superimage.dockerfile
      args:
        - version=20.10
    container_name: c3
    tty: true
    stdin_open: true
  c4s1:
    build:
      context: .
      dockerfile: superimage.dockerfile
      args:
        - version=22.10
    container_name: c4s1
    volumes:
      - ./server.sh:/server.sh
    command: "sh /server.sh"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: lab5
      
